version: "3.8"

services:
  mysql:
    image: mysql
    restart: unless-stopped
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: 92Pgigc3ps!
      MYSQL_DATABASE: book_store
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "mysql"]
      timeout: 10s
      retries: 5
      interval: 10s

  book-store:
    depends_on:
      - mysql
    restart: always
    image: online-book-store
    build: .
    env_file: ./.env
    ports:
      - "8081:8080"
      - "4040:4041"
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.datasource.url" : "jdbc:mysql://localhost:3306/book_store",
          "spring.datasource.password" : "92Pgigc3ps!",
          "spring.datasource.username" : "root",
          "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQLDialect"
        }'
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"