version: "3.8"

services:
  mysqldb:
    image: mysql
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
  online_book_store:
    depends_on:
      - mysqldb
    build: .
    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.hibernate.ddl-auto" : "$HIBERNATE_DDL_AUTO",
        "spring.jpa.show-sql" : "$SHOW_SQL",
        "springdoc.swagger-ui.disable-swagger-default-url" : "$DISABLE_SWAGGER_DEFAULT_URL",
        "springdoc.swagger-ui.path" : "$SWAGGER_PATH",
        "jwt.secret" : "$JWT_SECRET",
        "jwt.expiration" : "$JWT_EXPIRATION"
      }'
